# Generated by Django 4.2.7 on 2025-08-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer / End User'), ('editor', 'Editor'), ('chief_editor', 'Chief Editor')], default='customer', max_length=20),
        ),
    ]
