# Generated by Django 4.2.7 on 2025-09-16 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storychapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='storylike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='storychapter',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AddConstraint(
            model_name='storychapter',
            constraint=models.UniqueConstraint(fields=('story', 'order'), name='unique_story_order'),
        ),
        migrations.AddConstraint(
            model_name='storylike',
            constraint=models.UniqueConstraint(fields=('story', 'user'), name='unique_story_user_like'),
        ),
    ]
