# Generated by Django 4.2.7 on 2025-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_storychapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_banner',
            field=models.ImageField(blank=True, help_text='banner image for the story (chief editor only)', null=True, upload_to='story_banner/'),
        ),
    ]
