# Generated by Django 4.2.7 on 2025-08-22 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rssfeeditem',
            new_name='rss_feeds_r_publish_967bff_idx',
            old_name='rss_feeds_r_publish_8b8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='rssfeeditem',
            new_name='rss_feeds_r_source__1f70c9_idx',
            old_name='rss_feeds_r_source__f8c8c8_idx',
        ),
        migrations.RenameIndex(
            model_name='rssfeeditem',
            new_name='rss_feeds_r_is_read_e3d7f7_idx',
            old_name='rss_feeds_r_is_read_8b8c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='rssfeeditem',
            new_name='rss_feeds_r_is_arch_e831fb_idx',
            old_name='rss_feeds_r_is_arch_8b8c8c_idx',
        ),
        migrations.AddField(
            model_name='feedfetchlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedfetchlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rssfeeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rssfeeditem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rssfeeditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
